# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-11 20:34
from __future__ import unicode_literals

import autoslug.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('slug', autoslug.fields.AutoSlugField(unique_with=('created', 'product', 'customer'))),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=32, verbose_name='Title')),
                ('slug', autoslug.fields.AutoSlugField(unique_with=('title',))),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('table', models.TextField()),
                ('confirmation_number', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Purchase',
                'verbose_name_plural': 'Purchased',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('country', models.CharField(choices=[('CAN', 'Canada'), ('USA', 'USA')], default='USA', max_length=9)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='shipping_address', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('total_amount', models.PositiveIntegerField(blank=True, null=True)),
                ('customer_name', models.CharField(max_length=120)),
                ('shipping_address', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=40)),
                ('postal_code', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('telephone', models.CharField(blank=True, max_length=15, null=True)),
                ('billing_email', models.EmailField(max_length=80)),
                ('cart_slug', autoslug.fields.AutoSlugField(unique_with=('created', 'customer'))),
                ('delivered', models.BooleanField(default=False)),
                ('payment_success', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Shipping Address',
            },
        ),
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=32, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('brand_url', models.URLField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Startup',
                'verbose_name_plural': 'Startups',
            },
        ),
        migrations.CreateModel(
            name='StartupColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('color', models.CharField(max_length=6, verbose_name='Color')),
                ('red', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('green', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('blue', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_color', to='startupconfort.Startup')),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colors',
            },
        ),
        migrations.CreateModel(
            name='StartupProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_score', models.IntegerField(db_index=True, default=0)),
                ('num_vote_up', models.PositiveIntegerField(db_index=True, default=0)),
                ('num_vote_down', models.PositiveIntegerField(db_index=True, default=0)),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=32, verbose_name='Title')),
                ('shortdesc', models.CharField(max_length=80, verbose_name='shortdesc')),
                ('slug', autoslug.fields.AutoSlugField(unique_with=('created', 'startup'))),
                ('price', models.IntegerField(default=28)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='Qty')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='StartupProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_score', models.IntegerField(db_index=True, default=0)),
                ('num_vote_up', models.PositiveIntegerField(db_index=True, default=0)),
                ('num_vote_down', models.PositiveIntegerField(db_index=True, default=0)),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('shortdesc', models.CharField(blank=True, max_length=80, null=True, verbose_name='shortdesc')),
            ],
            options={
                'verbose_name': 'StartupProductImage',
                'verbose_name_plural': 'StartupProductImages',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='StartupShopppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='Qty')),
                ('total_amount', models.PositiveIntegerField(blank=True, null=True)),
                ('shipping_address', models.CharField(blank=True, max_length=120, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=40, null=True)),
                ('cart_slug', autoslug.fields.AutoSlugField(unique_with=('created', 'product', 'color'))),
                ('delivered', models.BooleanField(default=False)),
                ('payment_success', models.BooleanField(default=False)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_cart_color', to='startupconfort.StartupColor')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shopping Cart',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('vote_score', models.IntegerField(db_index=True, default=0)),
                ('num_vote_up', models.PositiveIntegerField(db_index=True, default=0)),
                ('num_vote_down', models.PositiveIntegerField(db_index=True, default=0)),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='image', serialize=False, to='startupconfort.StartupProduct')),
                ('picture', stdimage.models.StdImageField(blank=True, null=True, upload_to='startup-product/%Y/%m/%d', verbose_name='pics')),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Galleries',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='startupshopppingcart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_cart_product', to='startupconfort.StartupProduct'),
        ),
        migrations.AddField(
            model_name='startupshopppingcart',
            name='startup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_cart_startup', to='startupconfort.StartupProduct'),
        ),
        migrations.AddField(
            model_name='startupproduct',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='startupconfort.Category'),
        ),
        migrations.AddField(
            model_name='startupproduct',
            name='startup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_product', to='startupconfort.Startup'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startupconfort.StartupProduct'),
        ),
    ]
