# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-11 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startupconfort', '0002_auto_20171111_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Title'),
        ),
    ]
