# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-22 01:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acceptance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('liner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stander', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acceptance',
                'verbose_name_plural': 'Acceptances',
            },
        ),
        migrations.CreateModel(
            name='LineezLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('latitude', models.CharField(max_length=40)),
                ('longitude', models.CharField(max_length=40)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Lineez_gps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='LineUpPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=32, verbose_name='Title')),
                ('description', models.CharField(max_length=32, verbose_name='Description')),
                ('time_host_will_be_there', models.DateTimeField(verbose_name='time_host_will_be_there')),
                ('time_host_wants_to_be_there', models.DateTimeField(verbose_name='time_host_wants_to_be_there')),
                ('time_guest_must_be_there', models.DateTimeField(verbose_name='time_guest_must_be_there')),
                ('address', models.CharField(max_length=150, verbose_name='Address')),
                ('price', models.PositiveIntegerField(default=10)),
                ('min_garanty_for_guest', models.PositiveIntegerField()),
                ('min_garanty_for_host', models.PositiveIntegerField()),
                ('latitude', models.CharField(max_length=32, verbose_name='Latitude')),
                ('longitude', models.CharField(max_length=32, verbose_name='Longitude')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'LineupPost',
                'verbose_name_plural': 'LineupPosts',
            },
        ),
        migrations.AddField(
            model_name='acceptance',
            name='lineup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineup', to='lineez.LineUpPost'),
        ),
        migrations.AddField(
            model_name='acceptance',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requester', to=settings.AUTH_USER_MODEL),
        ),
    ]
