# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-22 01:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wadiyabi', '0002_auto_20170821_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wadiyabi_bank', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wadiyabicomment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wadiyabi_commentaire', to='wadiyabi.WadiyabiProduct'),
        ),
        migrations.AlterField(
            model_name='wadiyabicomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wadiyabi_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wadiyabiuserprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wadiyabi_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
