# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-22 02:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wadiyabi', '0003_auto_20170821_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wadiyabilocation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps', to=settings.AUTH_USER_MODEL),
        ),
    ]
