# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-23 03:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wadiyabi', '0004_auto_20170821_2205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wadiyabipurchase',
            old_name='post',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='wadiyabilocation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Location_gps', to=settings.AUTH_USER_MODEL),
        ),
    ]
