# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-13 17:48
from __future__ import unicode_literals

import applications.brandcolors.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', applications.brandcolors.models.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', applications.brandcolors.models.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('picture', stdimage.models.StdImageField(blank=True, null=True, upload_to='fabrics/%Y/%m/%d', verbose_name='pics')),
            ],
            options={
                'verbose_name': 'Fabric',
                'verbose_name_plural': 'Fabric',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', applications.brandcolors.models.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', applications.brandcolors.models.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('brand_url', models.URLField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Startup',
                'verbose_name_plural': 'Startups',
            },
        ),
        migrations.CreateModel(
            name='StartupColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', applications.brandcolors.models.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', applications.brandcolors.models.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('color', models.CharField(max_length=6, verbose_name='Color')),
                ('red', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('green', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('blue', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_color', to='brandcolors.Startup')),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colors',
            },
        ),
    ]
